#!/usr/bin/env bash
#This script display Best School 10 times and add bad luck on the fourth iteration and good luck on 8th iteration

i=1
while [ $i -le 10 ]; do
if [ $i -eq 4 ]; then
echo "bad luck"
elif [ $i -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
