#!/usr/bin/env bash
#This script return with decision whether the file exists or not.

#check if the file/directory 'school' exists
if [ -e school ]; then
# print if it is a regular file first
if [ -f school ]; then
echo "school is a regular file"
fi
echo "school file exists"

#check if empty
if [ -s school ]; then
echo "school file is not empty"
else
echo "school file is empty"
fi
else
echo "school file does not exist"
fi
