#!/usr/bin/env bash
# Display PID and process name of processes whose name contains "bash"

for pid in /proc/[0-9]*; do
    cmd=$(basename "$(readlink -f "$pid/exe" 2>/dev/null)" 2>/dev/null)
    if [[ $cmd == *bash* ]]; then
        echo "$(basename "$pid") $cmd"
    fi
done
